print('Install necessary package')
install.packages('golem') 
install.packages("BiocManager")

BiocManager::install("DESeq2",update=FALSE)
BiocManager::install("clusterProfiler",update=FALSE)
BiocManager::install("DOSE",update=FALSE)
BiocManager::install("ReactomePA",update=FALSE)
BiocManager::install("enrichplot",update=FALSE)
BiocManager::install("pathview",update=FALSE)
BiocManager::install("GO.db",update=FALSE)
BiocManager::install("ggpubr",update=FALSE)
BiocManager::install("heatmaply",update=FALSE)